name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04

    outputs:
      output1: ${{ steps.step1 }}
    steps:
      - name: Read README.md
        id: read
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      - id: step1
        run: echo steps.read >> $GITHUB_OUTPUT

      - name: output pipeline
        id: cowsay_output_id # You want id
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ${{ steps.step1 }}
          cow: 'gopher' # ascii art list: https://github.com/Code-Hex/Neo-cowsay/tree/master/cows
          cowsay_to_output: 'cowsay'
        
      - name: print output
        run: |
          echo "${{ steps.cowsay_output_id.outputs.cowsay }}"